package Telas;

import Classes.Cordas;
import Classes.Percussao;
import Classes.Sopro;
import Servicos.ServicoInstrumento;
import javax.swing.JOptionPane;

public class CadastrarInstrumento extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarInstrumento
     */
    public CadastrarInstrumento() {
        initComponents();
        ServicoInstrumento.desabilitarPanel(panelCordas);
        ServicoInstrumento.desabilitarPanel(panelPercussao);
        ServicoInstrumento.desabilitarPanel(panelSopro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGerais = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldCor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldQuantidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldPreco = new javax.swing.JTextField();
        panelCaracteristicas = new javax.swing.JPanel();
        panelCordas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fieldQtdCordas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldBraco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldCorpo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fieldOrigem = new javax.swing.JTextField();
        panelPercussao = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fieldQtdPratos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldMadeira = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fieldCaixa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fieldToms = new javax.swing.JTextField();
        panelSopro = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        fieldMaterial = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fieldAcabamento = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fieldAfinacao = new javax.swing.JTextField();
        botaoCancelar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();

        setTitle("Cadastrar Instrumento");

        panelGerais.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Gerais"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Cor:");

        jLabel3.setText("Marca:");

        jLabel4.setText("Quantidade:");

        jLabel5.setText("Preço:");

        javax.swing.GroupLayout panelGeraisLayout = new javax.swing.GroupLayout(panelGerais);
        panelGerais.setLayout(panelGeraisLayout);
        panelGeraisLayout.setHorizontalGroup(
            panelGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeraisLayout.createSequentialGroup()
                .addGroup(panelGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeraisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldMarca))
                    .addGroup(panelGeraisLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(fieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPreco)))
                .addContainerGap())
        );
        panelGeraisLayout.setVerticalGroup(
            panelGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(fieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeraisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(panelGeraisLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(panelGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(fieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(fieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCaracteristicas.setBorder(javax.swing.BorderFactory.createTitledBorder("Características"));

        panelCordas.setBorder(javax.swing.BorderFactory.createTitledBorder("Cordas"));

        jLabel7.setText("Quantidade de Cordas:");

        jLabel8.setText("Tipo do Braço:");

        jLabel9.setText("Tipo do Corpo:");

        jLabel17.setText("Origem:");

        javax.swing.GroupLayout panelCordasLayout = new javax.swing.GroupLayout(panelCordas);
        panelCordas.setLayout(panelCordasLayout);
        panelCordasLayout.setHorizontalGroup(
            panelCordasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCordasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCordasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCordasLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldQtdCordas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCordasLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldOrigem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldBraco, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCorpo)
                .addContainerGap())
        );
        panelCordasLayout.setVerticalGroup(
            panelCordasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCordasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCordasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldQtdCordas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(fieldBraco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(fieldCorpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(panelCordasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(fieldOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelPercussao.setBorder(javax.swing.BorderFactory.createTitledBorder("Percussão"));

        jLabel10.setText("Quantide de Pratos:");

        jLabel11.setText("Tipo da Madeira:");

        jLabel12.setText("Dimensão da Caixa:");

        jLabel13.setText("Dimensão dos Toms:");

        javax.swing.GroupLayout panelPercussaoLayout = new javax.swing.GroupLayout(panelPercussao);
        panelPercussao.setLayout(panelPercussaoLayout);
        panelPercussaoLayout.setHorizontalGroup(
            panelPercussaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPercussaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPercussaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPercussaoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldQtdPratos))
                    .addGroup(panelPercussaoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldMadeira, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldToms, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPercussaoLayout.setVerticalGroup(
            panelPercussaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPercussaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPercussaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldQtdPratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(fieldCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(fieldToms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPercussaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fieldMadeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSopro.setBorder(javax.swing.BorderFactory.createTitledBorder("Sopro"));

        jLabel14.setText("Material:");

        jLabel15.setText("Acabamento:");

        jLabel16.setText("Afinação:");

        javax.swing.GroupLayout panelSoproLayout = new javax.swing.GroupLayout(panelSopro);
        panelSopro.setLayout(panelSoproLayout);
        panelSoproLayout.setHorizontalGroup(
            panelSoproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoproLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldAcabamento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldAfinacao)
                .addContainerGap())
        );
        panelSoproLayout.setVerticalGroup(
            panelSoproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoproLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSoproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fieldMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(fieldAcabamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(fieldAfinacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCaracteristicasLayout = new javax.swing.GroupLayout(panelCaracteristicas);
        panelCaracteristicas.setLayout(panelCaracteristicasLayout);
        panelCaracteristicasLayout.setHorizontalGroup(
            panelCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaracteristicasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCordas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPercussao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSopro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCaracteristicasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCaracteristicasLayout.setVerticalGroup(
            panelCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaracteristicasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCordas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPercussao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSopro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Tipo:");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Cordas", "Percussão", "Sopro" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCaracteristicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelGerais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed

        if (comboTipo.getSelectedItem().equals("Cordas")) {
            ServicoInstrumento.habilitarPanel(panelCordas);
            ServicoInstrumento.desabilitarPanel(panelSopro);
            ServicoInstrumento.desabilitarPanel(panelPercussao);
        } else if (comboTipo.getSelectedItem().equals("Percussão")) {
            ServicoInstrumento.habilitarPanel(panelPercussao);
            ServicoInstrumento.desabilitarPanel(panelSopro);
            ServicoInstrumento.desabilitarPanel(panelCordas);
        } else if (comboTipo.getSelectedItem().equals("Sopro")) {
            ServicoInstrumento.habilitarPanel(panelSopro);
            ServicoInstrumento.desabilitarPanel(panelCordas);
            ServicoInstrumento.desabilitarPanel(panelPercussao);
        }
    }//GEN-LAST:event_comboTipoActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed

        if (comboTipo.getSelectedItem().equals("Cordas")) {
            Cordas instrumento = new Cordas();
            instrumento.setNome(fieldNome.getText());
            instrumento.setMarca(fieldMarca.getText());
            instrumento.setCor(fieldCor.getText());
            try {
                instrumento.setPreco(Double.parseDouble(fieldPreco.getText().replaceAll(",", ".")));
                instrumento.setQuantidade(Integer.parseInt(fieldQuantidade.getText()));
            } catch (Exception ex) {
            }
            instrumento.setTipo((String) comboTipo.getSelectedItem());
            instrumento.setQtdCordas(fieldQtdCordas.getText());
            instrumento.setTipoBraco(fieldBraco.getText());
            instrumento.setTipoCorpo(fieldCorpo.getText());
            instrumento.setOrigem(fieldOrigem.getText());
            try {
                ServicoInstrumento.cadastrarInstrmento(instrumento);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(), "ERRO",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(rootPane, "Instrumento cadastrado com sucesso!",
                    "Cadastro efetuado", JOptionPane.INFORMATION_MESSAGE);
        } else if (comboTipo.getSelectedItem().equals("Percussão")) {
            Percussao instrumento = new Percussao();
            instrumento.setNome(fieldNome.getText());
            instrumento.setMarca(fieldMarca.getText());
            instrumento.setCor(fieldCor.getText());
            try {
                instrumento.setPreco(Double.parseDouble(fieldPreco.getText().replaceAll(",", ".")));
                instrumento.setQuantidade(Integer.parseInt(fieldQuantidade.getText()));
            } catch (Exception ex) {
            }
            instrumento.setTipo((String) comboTipo.getSelectedItem());
            instrumento.setQtdPratos(fieldQtdPratos.getText());
            instrumento.setTipoMadeira(fieldMadeira.getText());
            instrumento.setDimensaoCaixa(fieldCaixa.getText());
            instrumento.setDimensaoToms(fieldToms.getText());
            try {
                ServicoInstrumento.cadastrarInstrmento(instrumento);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(), "ERRO",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(rootPane, "Instrumento cadastrado com sucesso!",
                    "Cadastro efetuado", JOptionPane.INFORMATION_MESSAGE);
        } else if (comboTipo.getSelectedItem().equals("Sopro")) {
            Sopro instrumento = new Sopro();
            instrumento.setNome(fieldNome.getText());
            instrumento.setMarca(fieldMarca.getText());
            instrumento.setCor(fieldCor.getText());
            try {
                instrumento.setPreco(Double.parseDouble(fieldPreco.getText().replaceAll(",", ".")));
                instrumento.setQuantidade(Integer.parseInt(fieldQuantidade.getText()));
            } catch (Exception ex) {
            }
            instrumento.setTipo((String) comboTipo.getSelectedItem());
            instrumento.setMaterial(fieldMaterial.getText());
            instrumento.setAcabamento(fieldAcabamento.getText());
            instrumento.setAfinacao(fieldAfinacao.getText());
            try {
                ServicoInstrumento.cadastrarInstrmento(instrumento);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(), "ERRO",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(rootPane, "Instrumento cadastrado com sucesso!",
                    "Cadastro efetuado", JOptionPane.INFORMATION_MESSAGE);
        }
        limparCampos();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    public void limparCampos() {
        fieldNome.setText("");
        fieldMarca.setText("");
        fieldCor.setText("");
        fieldPreco.setText("");
        fieldQuantidade.setText("");
        comboTipo.setSelectedItem("Selecione");
        fieldQtdCordas.setText("");
        fieldBraco.setText("");
        fieldCorpo.setText("");
        fieldOrigem.setText("");
        fieldQtdPratos.setText("");
        fieldMadeira.setText("");
        fieldCaixa.setText("");
        fieldToms.setText("");
        fieldMaterial.setText("");
        fieldAcabamento.setText("");
        fieldAfinacao.setText("");
        ServicoInstrumento.desabilitarPanel(panelCordas);
        ServicoInstrumento.desabilitarPanel(panelPercussao);
        ServicoInstrumento.desabilitarPanel(panelSopro);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JTextField fieldAcabamento;
    private javax.swing.JTextField fieldAfinacao;
    private javax.swing.JTextField fieldBraco;
    private javax.swing.JTextField fieldCaixa;
    private javax.swing.JTextField fieldCor;
    private javax.swing.JTextField fieldCorpo;
    private javax.swing.JTextField fieldMadeira;
    private javax.swing.JTextField fieldMarca;
    private javax.swing.JTextField fieldMaterial;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldOrigem;
    private javax.swing.JTextField fieldPreco;
    private javax.swing.JTextField fieldQtdCordas;
    private javax.swing.JTextField fieldQtdPratos;
    private javax.swing.JTextField fieldQuantidade;
    private javax.swing.JTextField fieldToms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelCaracteristicas;
    private javax.swing.JPanel panelCordas;
    private javax.swing.JPanel panelGerais;
    private javax.swing.JPanel panelPercussao;
    private javax.swing.JPanel panelSopro;
    // End of variables declaration//GEN-END:variables
}
